name: Update issues

on:
  issues:
    types: [opened]
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jonahgoldwastaken/issue-branch@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name_pattern: issue-{number}
