name: New Branch Trigger

on:
  create:
    branches:
      - 'GH-[0-9]+'

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract Number
        id: extract-number
        run: |
          BRANCH_NAME=${{ github.ref }}
          NUMBER_REGEX='GH-([0-9]+)'
          
          if [[ $BRANCH_NAME =~ $NUMBER_REGEX ]]; then
            echo "Extracted Number: ${BASH_REMATCH[1]}"
            echo "issue=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "Failed to extract number from branch name"
            exit 1
          fi
      - name: Run a command
        run: |
          echo "Extracted Number: ${{ steps.extract-number.outputs.issue }}"
      - name: update issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const number = "${{ steps.extract-number.outputs.issue }}";
            const octokit = context.github;
            const { data: issue } = await octokit.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
            });
            await octokit.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              state: 'open',
              labels: issue.labels.map(label => label.name),
              assignees: issue.assignees.map(assignee => assignee.login),
              title: issue.title,
              body: issue.body,
              milestone: issue.milestone,
              assignee: issue.assignee ? issue.assignee.login : null,
              status: 'In Progress',
            });
#      - name: Update issue
#        uses: actions-cool/issues-helper@v3
#        with:
#          actions: 'update-issue'
#          token: ${{ secrets.GITHUB_TOKEN }}
#          issue-number: ${{ steps.extract-number.outputs.issue }}
#          state: 'closed'
