name: Add PR to project
on:
  push
permissions:
  actions: read
  pull-requests: read
  contents: read
  issues: write
  repository-projects: write
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        id: project_data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '${{ toJSON(github) }}';
          echo '${{ toJSON(job) }}';
          echo '${{ toJSON(steps) }}';
          echo '${{ toJSON(runner) }}';
          echo '${{ toJSON(strategy) }}';
          echo '${{ toJSON(matrix) }}';
          gh api graphql -F owner="astavelopment" -F repo="test-workflow" -F query='query ($owner: String!, $repo: String!) {
            repository(owner: $owner, name: $repo) {
              issues(first: 100) {
                nodes {
                 number
                 title
                }
              }
            }
          }' | jq -r '.'
