name: New Branch Trigger

on:
  create:
    branches:
      - 'GH-[0-9]+'

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Number
        id: extract-number
        run: |
          BRANCH_NAME=${{ github.ref }}
          NUMBER_REGEX='GH-([0-9]+)'
          
          if [[ $BRANCH_NAME =~ $NUMBER_REGEX ]]; then
            echo "Extracted Number: ${BASH_REMATCH[1]}"
            echo "::set-output name=number::${BASH_REMATCH[1]}"
          else
            echo "Failed to extract number from branch name"
            exit 1
          fi

      #- name: Run a command
      #  run: echo "This workflow was triggered by the creation of a branch with the specified prefix. Extracted Number: ${{ steps.extract-number.outputs.number }}"
