name: Add PR to project
on:
  push
permissions:
  actions: read
  pull-requests: read
  contents: read
  issues: write
  repository-projects: write
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        id: project_data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql -F owner="${{github.repository_owner}}" -F repo="${{github.event.repository.name}}" -F query='query ($owner: String!, $repo: String!) {
            repository(owner: $owner, name: $repo) {
              issues(first: 100) {
                nodes {
                 number
                 title
                }
              }
            }
          }' | jq -r '.'
